### PR TITLE
Update Minion_Job_DigMineStairwell.java

### PR DESCRIPTION
**Pull request by BorisSFR**
The added code will add cobblestone walls to the stairwell/staircase.

### CODE REVIEW

**Comment by BorisSFR** [comment]
Where ever the grid is generated needs to be updated to a 7x7 so it will show that the walls are included...

**Comment by AtomicStryker** [comment]
The relevant line would be atomicstryker/minions/client/MinionsClient.java:167

**Comment by BorisSFR** [comment]
Thanks Atomic I have updated that file with suggested changes as well.

**Comment by BorisSFR** [comment]
Atomic, in the MinionsClient.java I have also added commented code that would offset the grid a different way.  If you like this suggestion better I can reedit my suggestion in the DigMineStairwell to accomplish this.

**Pull request closed without merging**
