### PR TITLE
[Ruins] update to Minecraft 1.15.2/Forge 31.2.0

### PR DESCRIPTION
**Pull request by QuarterAnimal**
These changes bring Ruins up to 1.15.2, eliminate the need for coremod injection, clean up a few compiler warnings, and put zombies on pirate ships.

This resolves issue #350, as Ruins can now spawn in TerraForged dimensions. It also addresses a couple issues raised in CurseForge comments, such as why ruins don't spawn with TerraForged (again with the TerraForged!), why drowned spawners don't work on pirate ships, and can i haz 1.15.2.

### CODE REVIEW

**Comment by AtomicStryker** [comment]
Hi, same as in the other PR i did not see this at all, sorry. You removed the coremod dependency in the code, but you didn't remove the coremod files themselves?

**Comment by QuarterAnimal** [comment]
Which files do you mean? The files **coremods.json** and **ruinstransformer.js** are deleted under [4172a06](https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/pull/354/commits/4172a0659030061a811d8a06690d1d8e371cb511).

**Comment by QuarterAnimal** [comment]
I didn't merge this one myself because I figure migration to a new version is significant enough to warrant waiting for your consent. Plus I'm not able to push to Curse, so you'd have to intervene anyway.

**Comment by AtomicStryker** [comment]
Indeed they are, either i didn't scroll or i just missed them, my bad.

Technically 1.15.1 is is fully compatible to 1.15.2 (the reverse is probably also true), which is the reason i did not push new versions for 1.15.2

Let me merge this right now (i assume you tested this and made sure the new decoration hook works?), test it for 2 minutes, then ill push a version

**Comment by AtomicStryker** [comment]
Playtested it, seems to work fine (but boy did MC annoy me with ocean-only worlds today). I will push this version to curse momentarily :)

**Comment by AtomicStryker** [comment]
Done. From what i can tell of the download numbers the majority of players seems to be still using 1.12 ... by a HUGE margin

**Comment by QuarterAnimal** [comment]
I can believe it. A lot of popular mods didn't make the 1.13 leap (yet?), so I expect 1.12 is going to be lingering for a while.

My primary motivation here was to make Ruins compatible with emerging custom chunk generator mods, like TerraForged. Since it's no longer a coremod, it should play nicely with those. I also hope that, by following the established vanilla chunk decoration scheme (kind of...), we're a lot less vulnerable to being broken in future Minecraft and Forge versions. I have a feeling another big wave of worldgen changes is coming.

**Pull request merged**
