### PR TITLE
[BattleTowers] Fixing that torches drop?

### PR DESCRIPTION
**Pull request by Sanduhr32**
I assume its a bug that the torches drop on the ground. Well here is my fix!
If it is not a bug please dont scream at me!

### CODE REVIEW

**Comment by AtomicStryker** [comment]
Is there a particular reason your PR is on an outdated branch? And yes it is a fix and i welcome solutions

**Comment by Sanduhr32** [comment]
Well i have a project (i test it for someone) and it is on 1.10.2 so i just did it here (on 1.10). I guess you can copy paste it into every newer version / adapt your code yourself. I can do that for ya but it would be a PR for every "new" Minecraft version.

However you can adopt me as a collaborator for this for maybe 24 hours and i do it for you.

Its 10:42 pm for me so i may not respond some hours. ;)
I hope its no issue that it is on an outdated branch ^^"

PS: It was a pain in the ass for getting this project working in IntelliJ because the setup quite strange but i made it... Well compiling works nothing else but who needs more?
You can always contact me on [Discord](discordapp.com)! `⌛.exe ¯\_(ツ)_/¯#5785` is my username and discrim ;D

**Comment by AtomicStryker** [comment]
I've commited this into the current branch too.

**Comment by Sanduhr32** [comment]
Oh thank you :)
Your Mod is awesome keep it up.

**Pull request merged**
